name: Chaotic Force
favicon: null
layout_spectrum: 0.90538
typography_spectrum: 0.36898494814522564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6875
  lightness: 0.9343141436111182
  saturation: 0.2929182427469641
  rhythmicContrast: 0.9646838135086
purpose: []
